server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/barberia
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# JWT properties
jwt:
  secret: fluxemBarberiaSuperSecreto1234567890
  expiration: 86400000 # 1 día en milisegundos

# Springdoc / Swagger config
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  api-docs:
    path: /v3/api-docs

# CORS global config (si usas WebMvcConfigurer)
cors:
  allowed-origins: "*"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
